[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[build.environment]
  REACT_APP_BACKEND_URL = "https://iot-pp8j.onrender.com/"
